---
## Default Elasticsearch configuration from Elasticsearch base image.
## https://github.com/elastic/elasticsearch/blob/main/distribution/docker/src/docker/config/elasticsearch.yml
#
cluster.name: docker-cluster
network.host: 0.0.0.0

## X-Pack settings
## see https://www.elastic.co/guide/en/elasticsearch/reference/current/security-settings.html
#
xpack.license.self_generated.type: trial
xpack.security.enabled: true
xpack.security.http.ssl.enabled: true
xpack.security.http.ssl.key: "/etc/pki/elasticsearch/elasticsearch.key"  # Path to your private key
xpack.security.http.ssl.certificate: "/etc/pki/elasticsearch/elasticsearch.crt"  # Path to your certificate
xpack.security.http.ssl.certificate_authorities: ["/etc/pki/elasticsearch/ca.crt"]  # Path to your CA certificate
xpack.security.http.ssl.verification_mode: full 
