heat_template_version: 2013-05-23
description: 'Simple NRF Base HOT VNF'

parameters:
  nfv:
    type: json

resources:
  NRF:
    type: NRF.yaml
    properties:
      flavor: { get_param: [ nfv, VDU, NRF, computeFlavourId ] }
      image: { get_param: [ nfv, VDU, NRF, vcImageId ] }
      ip: { get_param: [ nfv, input, nfs, mysql, ip ]}
      elk_network: { get_param: [ nfv, input, networks, elk_net, id ]}
      5g_network: { get_param: [ nfv, input, networks, 5g_net, id ] }
      elk_ip: { get_param: [ nfv, input, elk, ip ] }
      mysql_ip: { get_param: [ nfv, input, nfs, mysql, ip ]}
      filebeat_password: { get_param: [ nfv, input, elk, filebeat_password ] }
      beats_password: { get_param: [ nfv, input, elk, beats_password ] }

outputs: {}