heat_template_version: 2013-05-23
description: 'NRF Base HOT VNF'

parameters:
  nfv:
    type: json

resources:

  NRF:
    type: NRF.yaml
    depends_on: MySQL
    properties:
      flavor: { get_param: [ nfv, VDU, NRF, computeFlavourId ] }
      image: { get_param: [ nfv, VDU, NRF, vcImageId ] }
      elk_network: { get_attr: [ elk_net, elk_net ]}
      5g_network: { get_attr: [ 5g_net, 5g_net ] }
      elk_ip: { get_param: [ nfv, input, elk, ip ] }
      mysql_ip: { get_attr: [ MySQL, MySQL_IP ]}
      filebeat_password: { get_param: [ nfv, input, elk, filebeat_ps ] }
      beats_password: { get_param: [ nfv, input, elk, beats_ps ] }

outputs: {}