version: '3.8'

services:

  oai-smf:
    container_name: "oai-smf"
    image: oaisoftwarealliance/oai-smf:v2.0.1
    volumes:
        - ./nf/conf/basic_nrf_config.yaml:/openair-smf/etc/config.yaml
    environment:
        - TZ=Europe/Paris
    privileged: true
    network_mode: "host"