#!/bin/bash

set -eux

##################################### UERANSIM Installation #####################################
apt update
apt upgrade

apt install make
apt install gcc
apt install g++
apt install libsctp-dev lksctp-tools
apt install iproute2
apt install cmake

git clone https://github.com/aligungr/UERANSIM

cd UERANSIM
make
cd ..

# Define paths
TARGET_DIR=/opt/prototype_master
SOURCE_DIR=$(dirname $0)/../files

mkdir -p $TARGET_DIR

cp -r $SOURCE_DIR/ueransim $TARGET_DIR

sudo chmod +x UERANSIM/build/nr-binder

##################################### Traffic Generation Scripts #####################################
# Install python dependencies
pip install subprocess
pip install selenium paho-mqtt
pip install selenium

# Install firefox
apt install xdg-utils
apt install firefox -y
apt install firefox-geckodriver

cp -r $SOURCE_DIR/traffic_generation $TARGET_DIR