#!/bin/bash

set -eux

apt update
apt upgrade

apt install make
apt install gcc
apt install g++
apt install libsctp-dev lksctp-tools
apt install iproute2
apt install cmake  # Install CMake using APT instead of Snap

git clone https://github.com/aligungr/UERANSIM

cd UERANSIM
make
cd ..

# Define paths
TARGET_DIR=/opt/prototype_master
SOURCE_DIR=$(dirname $0)/../files

mkdir -p $TARGET_DIR

cp -r $SOURCE_DIR/ueransim $TARGET_DIR

sudo chmod +x $TARGET_DIR/ueransim/entrypoint.sh