heat_template_version: 2013-05-23
description: 'SMF HOT for Sample VNF'

parameters:
  flavor:
    type: string
  image:
    type: string

  5g_network:
    type: string
  mysql_ip:
    type: string
  nrf_ip:
    type: string
  3GPP_ip:
    type: string
  ip:
    type: string

  elk_network:
    type: string
  elk_ip:
    type: string
  filebeat_password:
    type: string
  beats_password:
    type: string
  id:
    type: string
  
  external_network:
    type: string
  

resources:

  SMF:
    type: OS::Nova::Server
    properties:
      flavor: { get_param: flavor }
      image: { get_param: image }
      name: SMF
      networks:
        - port:
            get_resource: 5g_CP
        - port:
            get_resource: elk_CP
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #!/bin/bash

            sudo useradd -m -s /bin/bash nathan
            echo "nathan:stupid" | sudo chpasswd
            echo "nathan ALL=(ALL) NOPASSWD:ALL" | sudo tee -a /etc/sudoers

            ELK_IP=$PARAM_0
            MYSQL_IP=$PARAM_1
            NRF_IP=$PARAM_2
            echo "$ELK_IP elasticsearch" >> /etc/hosts
            echo "$ELK_IP logstash" >> /etc/hosts
            echo "$MYSQL_IP mysql" >> /etc/hosts
            echo "$NRF_IP oai-nrf" >> /etc/hosts
            
            export FILEBEAT_INTERNAL_PASSWORD=$PARAM_3
            export BEATS_SYSTEM_PASSWORD=$PARAM_4
            export VNF_TYPE="smf"
            export VNF_ID=$PARAM_5
            export GPP_NETWORK=$PARAM_6

            export PATH=$PATH:/opt/zeek/bin
            # Start the filebeat service
            filebeat &

            # Start the zeek service
            zeekctl deploy

            # Starting smf
            TARGET_DIR=/opt/prototype_master
            docker compose -f $TARGET_DIR/prototype_compose/docker-compose-smf.yml up -d

          params:
            $PARAM_0: { get_param: elk_ip }
            $PARAM_1: { get_param: mysql_ip }
            $PARAM_2: { get_param: nrf_ip }
            $PARAM_3: { get_param: filebeat_password }
            $PARAM_4: { get_param: beats_password }
            $PARAM_5: { get_param: id }
            $PARAM_6: { get_param: 3GPP_ip }
      

  5g_CP:
    type: OS::Neutron::Port
    properties:
      network: { get_param: 5g_network }
      port_security_enabled: false
      fixed_ips:
        - ip_address: { get_param: ip }

  5g_extvCP:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: public

  5g_association:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: 5g_extvCP }
      port_id: { get_resource: 5g_CP }

  elk_CP:
    type: OS::Neutron::Port
    properties:
      network: { get_param: elk_network }
      port_security_enabled: false
  
  elk_extvCP:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: public

  elk_association:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: elk_extvCP }
      port_id: { get_resource: elk_CP }
