heat_template_version: 2013-05-23
description: 'Base HOT for VNF'

parameters:
  nfv:
    type: json

resources:
  # Networks
  # internal network for NGINX Proxy <-> NF communication HTTP/HTTPS
  internal_net:
    type: OS::Neutron::Net
    properties:
      name: internal_net
      admin_state_up: true
      value_specs:
        mtu: 1450

  # Subnets
  # Subnet for the internal network
  int_subnet:
    type: OS::Neutron::Subnet
    depends_on: [ internal_net ]
    properties:
      name: proxy_vdu_int_subnet
      network: { get_resource: internal_net }
      cidr: 192.168.0.0/24
      enable_dhcp: true
      gateway_ip: 192.168.0.254

  # VDUs
  # VDU for the NGINX Proxy with Filebeat
  Prototype:
    type: prototype.yaml
    properties:
      flavor: { get_param: [ nfv, VDU, Prototype, computeFlavourId ] }
      image: { get_param: [ nfv, VDU, Prototype, vcImageId ] }
      internal_net: { get_resource: internal_network }
      external_net: { get_param: [ nfv, Network, externalNetworkId ] }
      proxy_security_group: { get_resource: proxy_security_group }
  # VDU for the 5G Network Function / Might need to adjust this to work with existing VNFDs for 5G Network Functions with multiple VDUs
  NF:
    type: network_function.yaml
    properties:
      flavor: { get_param: [ nfv, VDU, NF, computeFlavourId ] }
      image: { get_param: [ nfv, VDU, NF, vcImageId ] }
      internal_net: { get_resource: internal_net }
      internal_security_group: { get_resource: internal_security_group }


outputs: {}