version: '3.8'

services:

  oai-amf:
    container_name: "oai-amf"
    image: oaisoftwarealliance/oai-amf:v2.0.1
    volumes:
        - ./nf/conf/basic_vpp_nrf_config.yaml:/openair-amf/etc/config.yaml
    environment:
        - TZ=Europe/Paris
        - INT_ALGO_LIST=["NIA1" , "NIA2"]
        - CIPH_ALGO_LIST=["NEA1" , "NEA2"]
    privileged: true
    network_mode: "host"
# public_net:
#     ipv4_address: 192.168.70.132