#!/bin/bash
# Copy necessary files from the element's files directory into the appropriate locations in the target filesystem.

set -eux

# Define paths
TARGET_DIR=/opt/prototype_master
SOURCE_DIR=$(dirname $0)/../files

mkdir -p $TARGET_DIR
cp -r $SOURCE_DIR/elk_compose $TARGET_DIR
cp -r $SOURCE_DIR/ueransim_compose $TARGET_DIR

sudo chmod +x $TARGET_DIR/elk_compose/setup/entrypoint.sh