heat_template_version: 2013-05-23
description: 'NF HOT for Sample VNF'

parameters:
  flavor:
    type: string
  image:
    type: string
  net:
    type: string

resources:
  NF:
    type: OS::Nova::Server
    properties:
      flavor: { get_param: flavor }
      image: { get_param: image }
      name: Network Function
      networks:
        - port:
            get_resource: nf_internal_CP

  nf_internal_CP:
    type: OS::Neutron::Port
    properties:
      network: { get_param: net }
      security_groups:
          - test_secgrp