heat_template_version: 2013-05-23
description: 'Prototype HOT for Sample VNF'

parameters:
  flavor:
    type: string
  image:
    type: string
  net:
    type: string

resources:
  Prototype:
    type: OS::Nova::Server
    properties:
      flavor: { get_param: flavor }
      image: { get_param: image }
      name: prototype
      networks:
        - port:
            get_resource: external_CP
      user_data_format: RAW
      user_data: |
        #!/bin/bash
        sleep 30
        # Create a new user 'nathan'
        sudo useradd -m -s /bin/bash nathan
        # Set a password for the new user
        echo "nathan:stupid" | sudo chpasswd
        # Optionally, add the user to the sudoers file for administrative privileges
        echo "nathan ALL=(ALL) NOPASSWD:ALL" | sudo tee -a /etc/sudoers

        sudo /opt/prototype_v1/vm_entry_script.sh

  external_CP:
    type: OS::Neutron::Port
    properties:
      network: { get_param: net }
      port_security_enabled: false