#!/bin/bash
# Copy necessary files from the element's files directory into the appropriate locations in the target filesystem.

set -eux

apt update
apt upgrade

apt install make
apt install gcc
apt install g++
apt install libsctp-dev lksctp-tools
apt install iproute2
snap install cmake --classic

git clone https://github.com/aligungr/UERANSIM

# Define paths
TARGET_DIR=/opt/prototype_master
SOURCE_DIR=$(dirname $0)/../files

mkdir -p $TARGET_DIR
cp -r $SOURCE_DIR/elk_compose $TARGET_DIR

sudo chmod +x $TARGET_DIR/elk_compose/setup/entrypoint.sh