heat_template_version: 2013-05-23
description: 'ELK HOT for Sample VNF'

parameters:
  flavor:
    type: string
  image:
    type: string
  net:
    type: string

resources:
  ELK:
    type: OS::Nova::Server
    properties:
      flavor: { get_param: flavor }
      image: { get_param: image }
      name: elk
      networks:
        - port:
            get_resource: elk_CP
      user_data_format: RAW
      user_data: |
        #!/bin/bash
        sleep 30
        # Create a new user 'nathan'
        sudo useradd -m -s /bin/bash nathan
        # Set a password for the new user
        echo "nathan:stupid" | sudo chpasswd
        # Optionally, add the user to the sudoers file for administrative privileges
        echo "nathan ALL=(ALL) NOPASSWD:ALL" | sudo tee -a /etc/sudoers
        export ELASTIC_VERSION=8.15.0
        export ELASTIC_PASSWORD='elasticness'
        export LOGSTASH_INTERNAL_PASSWORD='in_the_logging_days'
        export KIBANA_SYSTEM_PASSWORD='kibanaNana'
        export FILEBEAT_INTERNAL_PASSWORD='filebeatNathan'
        export BEATS_SYSTEM_PASSWORD='beatsNathan'

        $TARGET_DIR=/opt/prototype_master/elk_compose
        sudo docker compose -f $TARGET_DIR/docker-compose.yml up setup
        sudo docker compose -f $TARGET_DIR/docker-compose.yml up -d

  elk_CP:
    type: OS::Neutron::Port
    properties:
      network: { get_param: net }
      port_security_enabled: false

  extvCP:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: public

  association:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: extvCP }
      port_id: { get_resource: elk_CP }