#!/bin/bash

set -e

# Add Zeek's repository and key for Ubuntu 22.04
echo 'deb http://download.opensuse.org/repositories/security:/zeek/xUbuntu_22.04/ /' | tee /etc/apt/sources.list.d/security:zeek.list
curl -fsSL https://download.opensuse.org/repositories/security:/zeek/xUbuntu_22.04/Release.key | gpg --dearmor | tee /etc/apt/trusted.gpg.d/security_zeek.gpg > /dev/null

# Update and install Zeek 6.0
apt update
apt install -y zeek-6.0

# Enable Zeek to start on boot
systemctl enable zeek

# Cleanup
apt-get clean
