heat_template_version: 2013-05-23
description: 'UDM HOT for Sample VNF'

parameters:
  flavor:
    type: string
  image:
    type: string

  5g_network:
    type: string
  mysql_ip:
    type: string
  nrf_ip:
    type: string
  udr_ip:
    type: string
  ip:
    type: string
  
  external_network:
    type: string

resources:

  UDM:
    type: OS::Nova::Server
    properties:
      flavor: { get_param: flavor }
      image: { get_param: image }
      name: UDM
      networks:
        - port:
            get_resource: 5g_CP
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #!/bin/bash

            sudo useradd -m -s /bin/bash nathan
            echo "nathan:stupid" | sudo chpasswd
            echo "nathan ALL=(ALL) NOPASSWD:ALL" | sudo tee -a /etc/sudoers

            MYSQL_IP=$PARAM_0
            NRF_IP=$PARAM_1
            UDR_IP=$PARAM_2
            echo "$MYSQL_IP mysql" >> /etc/hosts
            echo "$NRF_IP oai-nrf" >> /etc/hosts
            echo "$UDR_IP oai-udr" >> /etc/hosts

            # Starting udm
            TARGET_DIR=/opt/prototype_master
            docker compose -f $TARGET_DIR/prototype_compose/docker-compose-udm.yml up -d

          params:
            $PARAM_0: { get_param: mysql_ip }
            $PARAM_1: { get_param: nrf_ip }
            $PARAM_2: { get_param: udr_ip }

  5g_CP:
    type: OS::Neutron::Port
    properties:
      network: { get_param: 5g_network }
      port_security_enabled: false
      fixed_ips:
        - ip_address: { get_param: ip }

  5g_extvCP:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: public

  5g_association:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: 5g_extvCP }
      port_id: { get_resource: 5g_CP }
