version: '3.8'

services:

  gateway:
    build: 
      context: gateway
    privileged: true
    command: sh /entrypoint.sh
    container_name: gateway
    networks:
      external:
        ipv4_address: 172.18.0.2
      internal:
        ipv4_address: 172.20.0.2
    cap_add:
      - NET_ADMIN

  nf:
    build:
      context: nf
      # args:
      #   UBUNTU_VERSION: ${UBUNTU_VERSION}
      #   NETWORK_FUNCTION: ${NETWORK_FUNCTION}
    privileged: true
    command: sh /entrypoint.sh
    container_name: nf
    depends_on:
      - gateway
    networks:
      internal:
        ipv4_address: 172.20.0.3

  # filebeat:
  #   build:
  #     context: filebeat/
  #     args:
  #       ELASTIC_VERSION: ${ELASTIC_VERSION}
  #   container_name: filebeat
  #   user: root
  #   command:
  #     - -e
  #     - --strict.perms=false
  #   volumes:
  #     - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro,Z
  #     - ./gateway/logs:/var/log/gateway
  #     - ./nf/logs:/var/log/nf
  #     - type: bind
  #       source: /var/lib/docker/containers
  #       target: /var/lib/docker/containers
  #       read_only: true
  #     - type: bind
  #       source: /var/run/docker.sock
  #       target: /var/run/docker.sock
  #       read_only: true
  #   environment:
  #     FILEBEAT_INTERNAL_PASSWORD: ${FILEBEAT_INTERNAL_PASSWORD:-}
  #     BEATS_SYSTEM_PASSWORD: ${BEATS_SYSTEM_PASSWORD:-}
  #   networks:
  #     - elk

networks:
  external:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16

  internal:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16