heat_template_version: 2013-05-23
description: 'Prototype HOT for Sample VNF'

parameters:
  flavor:
    type: string
  image:
    type: string
  net1:
    type: string
  net2:
    type: string

resources:
  Prototype:
    type: OS::Nova::Server
    properties:
      flavor: { get_param: flavor }
      image: { get_param: image }
      name: Prototype
      networks:
        - port:
            get_resource: proxy_internal_CP
        - port:
            get_resource: proxy_external_CP

  proxy_internal_CP:
    type: OS::Neutron::Port
    properties:
      network: { get_param: net1 }

  proxy_external_CP:
    type: OS::Neutron::Port
    properties:
      network: { get_param: net2 }