heat_template_version: 2013-05-23
description: 'Prototype HOT for VNF'

parameters:
  flavor:
    type: string
  image:
    type: string
  internal_net:
    type: string
  external_net:
    type: string
  proxy_security_group:
    type: string

resources:
  Prototype:
    type: OS::Nova::Server
    properties:
      flavor: { get_param: flavor }
      image: { get_param: image }
      name: Prototype
      networks:
        - port: {get_resource: internal_port}
        - port: {get_resource: external_port}

  internal_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: internal_net }
      security_groups: [ { get_param: proxy_security_group } ]

  external_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: external_net }
      security_groups: [ { get_param: proxy_security_group } ]