heat_template_version: 2013-05-23
description: 'UERANSIM HOT for Sample VNF'

parameters:
  flavor:
    type: string
  image:
    type: string
  5g_network:
    type: string
  5g_access_network:
    type: string
  external_network:
    type: string
  ip: 
    type: string
  ip_access:
    type: string
  amf_ip:
    type: string

resources:

  UERANSIM:
    type: OS::Nova::Server
    properties:
      flavor: { get_param: flavor }
      image: { get_param: image }
      name: UERANSIM
      networks:
        - port:
            get_resource: 5g_CP
        - port:
            get_resource: 5g_access_CP
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #!/bin/bash

            sudo useradd -m -s /bin/bash nathan
            echo "nathan:stupid" | sudo chpasswd
            echo "nathan ALL=(ALL) NOPASSWD:ALL" | sudo tee -a /etc/sudoers
            
            export UERANSIM_IP_PUBLIC_NET=$PARAM_0
            export UERANSIM_IP_PUBLIC_NET_ACCESS=$PARAM_1
            export AMF_IP_PUBLIC_NET=$PARAM_2

            TARGET_DIR=/opt/prototype_master
            docker pull rohankharade/ueransim
            docker image tag rohankharade/ueransim:latest ueransim:latest
            # docker compose -f $TARGET_DIR/ueransim_compose/docker-compose-ueransim-vpp.yml up -d
            docker run -d --name ueransim --privileged --network host -e MCC=208 -e MNC=95 -e NCI=0x000000010 -e TAC=0xa000 -e LINK_IP=${UERANSIM_IP_PUBLIC_NET} -e NGAP_IP=${UERANSIM_IP_PUBLIC_NET} -e GTP_IP=${UERANSIM_IP_PUBLIC_NET_ACCESS} -e NGAP_PEER_IP=${AMF_IP_PUBLIC_NET} -e SST=222 -e SD=123 -e IGNORE_STREAM_IDS=true -e NUMBER_OF_UE=1 -e IMSI=208950000000031 -e KEY=0C0A34601D4F07677303652C0462535B -e OP=63bfa50ee6523365ff14c1f45f88737d -e OP_TYPE=OPC -e AMF_VALUE=8000 -e IMEI=356938035643803 -e IMEI_SV=0035609204079514 -e GNB_IP_ADDRESS=${UERANSIM_IP_PUBLIC_NET} -e PDU_TYPE=IPv4 -e APN=default -e SST_0=222 -e SD_0=123 -e SST_C=222 -e SD_C=123 -e SST_D=222 -e SD_D=123 --health-cmd="ifconfig uesimtun0" --health-interval=10s --health-timeout=5s --health-retries=5 ueransim:latest
          params:
            $PARAM_0: { get_param: ip }
            $PARAM_1: { get_param: ip_access }
            $PARAM_2: { get_param: amf_ip }

  5g_CP:
    type: OS::Neutron::Port
    properties:
      network: { get_param: 5g_network }
      port_security_enabled: false
      fixed_ips:
        - ip_address: { get_param: ip }

  5g_extvCP:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: public

  5g_access_CP:
    type: OS::Neutron::Port
    properties:
      network: { get_param: 5g_access_network }
      port_security_enabled: false
      fixed_ips:
        - ip_address: { get_param: ip_access }

  5g_access_extvCP:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: public

  5g_association:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: 5g_extvCP }
      port_id: { get_resource: 5g_CP }

  5g_access_association:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: 5g_access_extvCP }
      port_id: { get_resource: 5g_access_CP }
