heat_template_version: 2013-05-23
description: 'UERANSIM HOT for Sample VNF'

parameters:
  flavor:
    type: string
  image:
    type: string
  5g_network:
    type: string
  5g_access_network:
    type: string
  external_network:
    type: string
  ip: 
    type: string
  ip_access:
    type: string
  amf_ip:
    type: string

resources:

  UERANSIM:
    type: OS::Nova::Server
    properties:
      flavor: { get_param: flavor }
      image: { get_param: image }
      name: UERANSIM
      networks:
        - port:
            get_resource: 5g_CP
        - port:
            get_resource: 5g_access_CP
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #!/bin/bash

            sudo useradd -m -s /bin/bash nathan
            echo "nathan:stupid" | sudo chpasswd
            echo "nathan ALL=(ALL) NOPASSWD:ALL" | sudo tee -a /etc/sudoers

            export GNB_IP_ADDRESS=$PARAM_0
            export LINK_IP=$PARAM_0
            export NGAP_IP=$PARAM_0
            export GTP_IP=$PARAM_1
            export NGAP_PEER_IP=$PARAM_2
            export MCC=208
            export MNC=95
            export NCI=0x000000010
            export TAC=0xa000
            export SST=222
            export SST_R=222
            export SD=123
            export IGNORE_STREAM_IDS=true
            export KEY=0C0A34601D4F07677303652C0462535B
            export OP=63bfa50ee6523365ff14c1f45f88737d
            export OP_TYPE=OPC
            export AMF_VALUE=8000
            export PDU_TYPE=IPv4
            export APN=default
            export SST_0=222
            export SD_0=123
            export SST_C=222
            export SD_C=123
            export SST_D=222
            export SD_D=123

            # Run UERANSIM
            sudo /opt/prototype_master/ueransim/entrypoint.sh

          params:
            $PARAM_0: { get_param: ip }
            $PARAM_1: { get_param: ip_access }
            $PARAM_2: { get_param: amf_ip }

  5g_CP:
    type: OS::Neutron::Port
    properties:
      network: { get_param: 5g_network }
      port_security_enabled: false
      fixed_ips:
        - ip_address: { get_param: ip }

  5g_extvCP:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: public

  5g_access_CP:
    type: OS::Neutron::Port
    properties:
      network: { get_param: 5g_access_network }
      port_security_enabled: false
      fixed_ips:
        - ip_address: { get_param: ip_access }

  5g_access_extvCP:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: public

  5g_association:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: 5g_extvCP }
      port_id: { get_resource: 5g_CP }

  5g_access_association:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: 5g_access_extvCP }
      port_id: { get_resource: 5g_access_CP }
