heat_template_version: 2013-05-23
description: 'Suricata Base HOT for Sample VNF'

parameters:
  nfv:
    type: json

resources:
  Prototype:
    type: prototype.yaml
    properties:
      flavor: { get_param: [ nfv, VDU, Prototype, computeFlavourId ] }
      image: { get_param: [ nfv, VDU, Prototype, vcImageId ] }
      net1: { get_resource: internalVL1 }
      net2: { get_param: [ nfv, input, external_VL_ID ] }
      net3: { get_param: [ nfv, input, elk_VL_ID ] }

  NF:
    type: network_function.yaml
    properties:
      flavor: { get_param: [ nfv, VDU, NF, computeFlavourId ] }
      image: { get_param: [ nfv, VDU, NF, vcImageId ] }
      net: { get_resource: internalVL1 }

  internalVL1:
    type: OS::Neutron::Net

  internalVL1_subnet:
    type: OS::Neutron::Subnet
    properties:
      ip_version: 4
      network:
        get_resource: internalVL1
      cidr: {get_param: [ nfv, input, internal_VL_CIDR ]}
      enable_dhcp: true
      gateway_ip: {get_param: [ nfv, input, internal_VL_GW ]}

outputs: {}