#!/bin/bash

set -eux

# Define paths
TARGET_DIR=/opt/prototype_master
SOURCE_DIR=$(dirname $0)/../files

mkdir -p $TARGET_DIR
cp -r $SOURCE_DIR/elk_compose $TARGET_DIR

sudo chmod +x $TARGET_DIR/elk_compose/setup/entrypoint.sh