heat_template_version: 2013-05-23
description: 'MySQL DB HOT for Sample VNF'

parameters:
  flavor:
    type: string
  image:
    type: string

  5g_network:
    type: string
  ip:
    type: string

  elk_network:
    type: string
  elk_ip:
    type: string
  filebeat_password:
    type: string
  beats_password:
    type: string
  id:
    type: string

  external_network:
    type: string
resources:

  MySQL:
    type: OS::Nova::Server
    properties:
      flavor: { get_param: flavor }
      image: { get_param: image }
      name: MySQL
      networks:
        - port:
            get_resource: 5g_CP
        - port:
            get_resource: elk_CP
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #!/bin/bash

            sudo useradd -m -s /bin/bash nathan
            echo "nathan:stupid" | sudo chpasswd
            echo "nathan ALL=(ALL) NOPASSWD:ALL" | sudo tee -a /etc/sudoers

            ELK_IP=$PARAM_0
            echo "$ELK_IP elasticsearch" >> /etc/hosts
            echo "$ELK_IP logstash" >> /etc/hosts

            export FILEBEAT_INTERNAL_PASSWORD=$PARAM_1
            export BEATS_SYSTEM_PASSWORD=$PARAM_2
            export VNF_TYPE="mysql"
            export VNF_ID=$PARAM_3

            export PATH=$PATH:/opt/zeek/bin
            # Start the filebeat service
            filebeat &

            # Start the zeek service
            zeekctl deploy

            # Starting mysql container
            TARGET_DIR=/opt/prototype_master
            docker compose -f $TARGET_DIR/prototype_compose/docker-compose-mysql.yml up -d
            
          params:
            $PARAM_0: { get_param: elk_ip }
            $PARAM_1: { get_param: filebeat_password }
            $PARAM_2: { get_param: beats_password }
            $PARAM_3: { get_param: id }

  5g_CP:
    type: OS::Neutron::Port
    properties:
      network: { get_param: 5g_network }
      port_security_enabled: false
      fixed_ips:
        - ip_address: { get_param: ip }

  5g_extvCP:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: public

  5g_association:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: 5g_extvCP }
      port_id: { get_resource: 5g_CP }

  elk_CP:
    type: OS::Neutron::Port
    properties:
      network: { get_param: elk_network }
      port_security_enabled: false
  
  elk_extvCP:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: public

  elk_association:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: elk_extvCP }
      port_id: { get_resource: elk_CP }
