@startuml

package "Web Application" {
  [Web Server] << (C,lightblue) >>
  [Application Server] << (C,lightgreen) >>
  [Database] << (C,lightyellow) >>
}

[Web Server] --> [Application Server] : "HTTP Requests"
[Application Server] --> [Database] : "SQL Queries"

@enduml
