heat_template_version: 2013-05-23
description: 'Simple AMF Base HOT VNF'

parameters:
  nfv:
    type: json

resources:
  AMF:
    type: AMF.yaml
    properties:
      flavor: { get_param: [ nfv, VDU, AMF, computeFlavourId ] }
      image: { get_param: [ nfv, VDU, AMF, vcImageId ] }

      5g_network: { get_param: [ nfv, input, networks, 5g_net, id ] }
      mysql_ip: { get_param: [ nfv, input, nfs, mysql, ip ] }
      nrf_ip: { get_param: [ nfv, input, nfs, nrf, ip ] }
      ausf_ip: { get_param: [ nfv, input, nfs, ausf, ip ] }
      udm_ip: { get_param: [ nfv, input, nfs, udm, ip ] }
      ip: { get_param: [ nfv, input, nfs, amf, ip ] }
      
      external_network: { get_param: [ nfv, input, networks, external, id ] }


outputs: {}