heat_template_version: 2013-05-23
description: 'Simple NRF Base HOT VNF'

parameters:
  nfv:
    type: json

resources:
  NRF:
    type: NRF.yaml
    properties:
      flavor: { get_param: [ nfv, VDU, NRF, computeFlavourId ] }
      image: { get_param: [ nfv, VDU, NRF, vcImageId ] }

      5g_network: { get_param: [ nfv, input, networks, 5g_net, id ] }
      ip: { get_param: [ nfv, input, nfs, nrf, ip ] }
      mysql_ip: { get_param: [ nfv, input, nfs, mysql, ip ] }

      external_network: { get_param: [ nfv, input, networks, external, id ] }

outputs: {}