heat_template_version: 2013-05-23
description: 'Simple EXT_DN Base HOT VNF'

parameters:
  nfv:
    type: json

resources:
  EXT_DN:
    type: EXT_DN.yaml
    properties:
      flavor: { get_param: [ nfv, VDU, EXT_DN, computeFlavourId ] }
      image: { get_param: [ nfv, VDU, EXT_DN, vcImageId ] }
      5g_access_network: { get_param: [ nfv, input, networks, 5g_access_net, id ] }
      external_network: { get_param: [ nfv, input, networks, external, id ] }
      ip: { get_param: [ nfv, input, nfs, ext_dn, ip ] }
      upf_ip_access: { get_param: [ nfv, input, nfs, upf, ip_access ] }

outputs: {}