heat_template_version: 2013-05-23
description: 'Simple MySQL Base HOT VNF'

parameters:
  nfv:
    type: json

resources:
  AUSF:
    type: AUSF.yaml
    properties:
      flavor: { get_param: [ nfv, VDU, AUSF, computeFlavourId ] }
      image: { get_param: [ nfv, VDU, AUSF, vcImageId ] }
      elk_network: { get_param: [ nfv, input, networks, elk_net, id ]}
      5g_network: { get_param: [ nfv, input, networks, 5g_net, id ] }
      external_network: { get_param: [ nfv, input, networks, external, id ]}
      elk_ip: { get_param: [ nfv, input, elk, ip ] }
      mysql_ip: { get_param: [ nfv, input, nfs, mysql, ip ]}
      nrf_ip: { get_param: [ nfv, input, nfs, nrf, ip ]}
      filebeat_password: { get_param: [ nfv, input, elk, filebeat_password ] }
      beats_password: { get_param: [ nfv, input, elk, beats_password ] }
      id: { get_param: [ nfv, input, nfs, ausf, id ] }
      ip: { get_param: [ nfv, input, nfs, ausf, ip ] }

outputs: {}