version: '3.8'

services:

  oai-amf:
    container_name: "oai-amf"
    image: oaisoftwarealliance/oai-amf:v2.0.1
    volumes:
        - ./nf/conf/basic_nrf_config.yaml:/openair-amf/etc/config.yaml
    environment:
        - TZ=Europe/Paris
    depends_on:
        - zeek
    privileged: true
    network_mode: "host"