#!/bin/bash
# Copy necessary files from the element's files directory into the appropriate locations in the target filesystem.

set -eux

pip install psutil
pip install requests

# Define paths
TARGET_DIR=/opt/prototype_master
SOURCE_DIR=$(dirname $0)/../files

# Create necessary directories in the target filesystem
mkdir -p $TARGET_DIR

# Copy the prototype_compose file to the appropriate directory in the target filesystem
cp -r $SOURCE_DIR/prototype_compose $TARGET_DIR
cp -r $SOURCE_DIR/resource_usage $TARGET_DIR

sudo chmod $TARGET_DIR/resource_usage/resource_check.sh