version: '3.8'

services:

  vpp-upf:
    privileged: true
    container_name: "vpp-upf"
    image: oaisoftwarealliance/oai-upf-vpp:v2.0.1
    environment:
      - IF_1_IP=${GPP_NETWORK}
      - IF_1_TYPE=N4
      - IF_2_IP=${IP_2}
      - IF_2_TYPE=N3
      - IF_2_NWI=access.oai.org
      - IF_3_IP=${IP_3}
      - IF_3_TYPE=N6
      - IF_3_IP_REMOTE=${EXT_DN_IP} # EXT-DN IP Address
      - IF_3_NWI=internet.oai.org
      - NAME=VPP-UPF
      - MNC=95
      - MCC=208
      - REALM=3gppnetwork.org
      - VPP_MAIN_CORE=0
      - VPP_CORE_WORKER=1
      - VPP_PLUGIN_PATH=/usr/lib/x86_64-linux-gnu/vpp_plugins/ # Ubuntu 18.04
      - SNSSAI_SD=00007B
      - SNSSAI_SST=222
      - DNN=default
      - REGISTER_NRF=yes
      - NRF_IP_ADDR=${NRF_IP_ADDR}
      - NRF_PORT=8080
      - HTTP_VERSION=2
    healthcheck:
      test: /bin/bash -c "pgrep vpp"
      interval: 10s
      timeout: 5s
      retries: 5
    network_mode: "host"