version: '3.8'

services:

  oai-udm:
    container_name: "oai-udm"
    image: oaisoftwarealliance/oai-udm:v2.0.1
    volumes:
        - ./nf/conf/basic_vpp_nrf_config.yaml:/openair-udm/etc/config.yaml
    environment:
        - TZ=Europe/Paris
    privileged: true
    network_mode: "host"
# public_net:
#     ipv4_address: 192.168.70.137